apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: sample
spec:
  clusterNetwork:
    services:
      cidrBlocks: ["10.112.0.0/12"]
    pods:
      cidrBlocks: ["10.17.0.0/16"]
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: sample-cp
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: KubridCluster
    name: sample
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: sample-cp
spec:
  replicas: 3
  version: 1.24.0
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: KubridMachineTemplate
      name: sample-cp
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          provider-id: kubrid://{{ ds.meta_data.instance_id }}
        ignorePreflightErrors:
          - SystemVerification
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          provider-id: kubrid://{{ ds.meta_data.instance_id }}
        ignorePreflightErrors:
          - SystemVerification
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: sample-md-0
spec:
  clusterName: sample
  replicas: 3
  selector: {}
  template:
    spec:
      clusterName: sample
      version: 1.24.0
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: sample-md-0
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: KubridMachineTemplate
        name: sample-md-0
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: sample-md-0
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            provider-id: kubrid://{{ ds.meta_data.instance_id }}
          ignorePreflightErrors:
            - SystemVerification
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: KubridCluster
metadata:
  name: sample
spec: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: KubridMachineTemplate
metadata:
  name: sample-cp
spec:
  template:
    spec: {}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: KubridMachineTemplate
metadata:
  name: sample-md-0
spec:
  template:
    spec: {}
